package com.umitytsr.peti.util

object Const {
    const val MESSAGES = "messages"
    const val DATE = "date"
    const val CHATS = "chats"
    const val PET_OWNER_EMAIL = "petOwnerEmail"
    const val PET_IMAGE = "petImage"
    const val PET_NAME = "petName"
    const val PET_TYPE = "petType"
    const val PET_SEX = "petSex"
    const val PET_GOAL = "petGoal"
    const val PET_AGE = "petAge"
    const val PET_VACCINATION = "petVaccination"
    const val PET_LOCATION = "petLocation"
    const val PET_BREED = "petBreed"
    const val PET_DESCRIPTION = "petDescription"
    const val PETS = "pets"
    const val USERS = "users"
    const val USER_EMAIL="userEmail"
    const val USER_FULL_NAME ="userFullName"
    const val USER_PHONE_NUMBER ="userPhoneNumber"
    const val USER_IMAGE = "userImage"
    const val SENDER = "sender"
}